# Generated by Django 4.2.7 on 2025-09-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={},
        ),
        migrations.RemoveField(
            model_name='certification',
            name='credential_id',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='issuer',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='verification_url',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='url',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='current_level',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='target_level',
        ),
        migrations.AddField(
            model_name='certification',
            name='certification_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='platform',
            field=models.CharField(blank=True, choices=[('coursera', 'Coursera'), ('udemy', 'Udemy'), ('edx', 'edX'), ('google', 'Google'), ('microsoft', 'Microsoft'), ('aws', 'AWS'), ('ibm', 'IBM'), ('oracle', 'Oracle'), ('cisco', 'Cisco'), ('comptia', 'CompTIA'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='provided_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='hours_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='resource',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='platform',
            field=models.CharField(choices=[('udemy', 'Udemy'), ('youtube', 'YouTube'), ('coursera', 'Coursera'), ('edx', 'edX'), ('khan_academy', 'Khan Academy'), ('freecodecamp', 'FreeCodeCamp'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='color',
            field=models.CharField(default='#8B5CF6', max_length=7),
        ),
        migrations.AddField(
            model_name='skill',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Easy'), (3, 'Medium'), (4, 'Hard'), (5, 'Expert')], default=1),
        ),
        migrations.AddField(
            model_name='skill',
            name='hours_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='skill',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('video', 'Video'), ('course', 'Course'), ('article', 'Article'), ('certification', 'Certification')], max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
